# Fill these in Streamlit Cloud > App > Settings > Secrets (preferred) or locally for testing.
SUPABASE_URL = "https://domgnztpibapfxqorcsv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbWduenRwaWJhcGZ4cW9yY3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzY2NjksImV4cCI6MjA3NzUxMjY2OX0.lc2YTywRRRQ6JDLCjvBOaQCIyWE2gKguQ7JjW8Rqg54"
ALPHAVANTAGE_KEY = "G5AWLDI4L0J98NBX"
BASE_CURRENCY = "CAD"
